### ISSUE TITLE
[Bug] setup.py install requires modelspec dependency to already be installed

### ISSUE THREAD

**Issue by mwatts15** [NeuroML/NeuroMLlite#27]
When doing an install of neuromllite from setup.py, setup.py imports neuromllite/__init__.py which in turn imports modelspec, but modelspec, in general, won't be installed, so the install fails.

**To Reproduce**
```
git clone git@github.com:neuroml/neuromllite.git
cd neuromllite
pip install .
```

**Expected behavior**
neuromllite is installed

**Observed behavior**
An error like this is returned:
```
Processing /work/neuromllite
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /work/neuromllite/env/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/work/neuromllite/setup.py'"'"'; __file__='"'"'/work/neuromllite/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-wvscttsa
       cwd: /work/neuromllite/
  Complete output (7 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/work/neuromllite/setup.py", line 3, in <module>
      import neuromllite
    File "/work/neuromllite/neuromllite/__init__.py", line 8, in <module>
      from modelspec.BaseTypes import Base
  ModuleNotFoundError: No module named 'modelspec'
  ----------------------------------------
WARNING: Discarding file:///work/neuromllite. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
**System information:**
 - OS: Linux x86_64
 - Python version (`python --version`): Python 3.9.9
 - Version of tools in use  (output of `nmllite-ui`): 0.4.1 (master branch)

**Comment by pgleeson** [comment]
Thanks for locating the source of the problem @mwatts15, it will help with a few other breaking builds...
