### ISSUE TITLE
[Bug] Stacktrace when running the first example

### ISSUE THREAD

**Issue by sanjayankur31** [NeuroML/NeuroMLlite#31]
**Describe the bug**
Stacktrace when running the first example

**To Reproduce**
Steps to reproduce the behavior, for example the command you used.

- download raw json file for example 1: https://github.com/NeuroML/NeuroMLlite/blob/master/examples/Example1_TestNetwork.json 
- run it with nmllite-ui

**Expected behavior**
Should run

**Observed behavior**
```
nmllite-ui Example1_TestNetwork.json
neuromllite >>> Loaded simulation specification from Example1_TestNetwork.json
Traceback (most recent call last):
  File "/usr/bin/nmllite-ui", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/neuromllite/gui/NMLliteUI.py", line 1302, in main
    nmlui = NMLliteUI(nml_sim_file)
  File "/usr/lib/python3.10/site-packages/neuromllite/gui/NMLliteUI.py", line 275, in __init__
    self.simulation = load_simulation_json(nml_sim_file)
  File "/usr/lib/python3.10/site-packages/neuromllite/utils.py", line 91, in load_simulation_json
    sim = _parse_element(data, sim)
  File "/usr/lib/python3.10/site-packages/modelspec/utils.py", line 73, in _parse_element
    to_build = _parse_attributes(dict_format[k], to_build)
  File "/usr/lib/python3.10/site-packages/modelspec/utils.py", line 109, in _parse_attributes
    type_to_use = to_build.allowed_fields[key][1]
KeyError: 'populations'
```
**System information:**
 - OS: [e.g. iOS] Fedora Linux 35
 - Python version (`python --version`) Python 3.10.2
 - Version of tools in use  (output of `nmllite-ui`) NMLlite-UI v0.4.2, modelspec-0.1.3

**Additional context**

**Comment by sanjayankur31** [comment]
Also getting it with the second example, so maybe it's a version mismatch somewhere :thinking: 

```
neuromllite >>> Loaded simulation specification from Example2_TestNetwork.json
Traceback (most recent call last):
  File "/usr/bin/nmllite-ui", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/neuromllite/gui/NMLliteUI.py", line 1302, in main
    nmlui = NMLliteUI(nml_sim_file)
  File "/usr/lib/python3.10/site-packages/neuromllite/gui/NMLliteUI.py", line 275, in __init__
    self.simulation = load_simulation_json(nml_sim_file)
  File "/usr/lib/python3.10/site-packages/neuromllite/utils.py", line 91, in load_simulation_json
    sim = _parse_element(data, sim)
  File "/usr/lib/python3.10/site-packages/modelspec/utils.py", line 73, in _parse_element
    to_build = _parse_attributes(dict_format[k], to_build)
  File "/usr/lib/python3.10/site-packages/modelspec/utils.py", line 109, in _parse_attributes
    type_to_use = to_build.allowed_fields[key][1]
KeyError: 'cells'
```

**Comment by pgleeson** [comment]
This si down to running nmllite-ui with the network file rather than the simulation file (which points to the network file). So basically like runnign pynml with the nml file not thhe lems simulation file...

**Comment by sanjayankur31** [comment]
PR #41 should handle this gracefully.
