### ISSUE TITLE
Crashing with Python 3.9

### ISSUE THREAD

**Issue by sanjayankur31** [NeuroML/NeuroMLlite#8]
Was just running it on a Python 3.9 system, and I see crashes:

```
 nmllite-ui NML2_FullNeuroML.nml 
QSocketNotifier: Can only be used with threads started with QThread
Traceback (most recent call last):
  File "/usr/bin/nmllite-ui", line 33, in <module>
    sys.exit(load_entry_point('neuromllite==0.2.1', 'console_scripts', 'nmllite-ui')())
  File "/usr/lib/python3.9/site-packages/neuromllite/gui/NMLliteUI.py", line 1225, in main
    nmlui = NMLliteUI(nml_sim_file)
  File "/usr/lib/python3.9/site-packages/neuromllite/gui/NMLliteUI.py", line 260, in __init__
    self.simulation = load_simulation_json(nml_sim_file)
  File "/usr/lib/python3.9/site-packages/neuromllite/utils.py", line 44, in load_simulation_json
    data = json.load(f, object_hook=ascii_encode_dict)
  File "/usr/lib64/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib64/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/usr/lib64/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

```
$ python3 --version
Python 3.9.0rc2
```

I can reproduce this in a new virtual env. It should be some encoding changes with python 3.9. I'll take a look.

**Comment by sanjayankur31** [comment]
Hrm, bad file from the looks of it. Closing.

**Comment by pgleeson** [comment]
Didn't even know there wasa  Python 3.9...

**Comment by sanjayankur31** [comment]
Yeh, the RCs are out. Expected release next month: 3.9.0 final: Monday, 2020-10-05
